### ISSUE TITLE
Separate actual source and visualizations better

### ISSUE THREAD

**Issue by ISSOtm** [vinheim3/tetris-gb-disasm#1]
Right now, the root directory is somewhat of a mash between the actual disassembly, and the web visualizations. I think it would be clearer if, at the root, there were only `disasm/`, `web/`, and `README.md` (plus some extra files if necessary.)

**Comment by vinheim3** [comment]
Advice always appreciated ISSOtm. I've definitely seen people typically split out the disassembler in a src/ directory for example, so I've split out mine appropriately. Please let me know if you think it needs something further. So far the usual processes work

**Comment by ISSOtm** [comment]
Good for me! :)
