### ISSUE TITLE
Consider re-licensing under an open source license?

### ISSUE THREAD

**Issue by Y2K-x** [vinheim3/tetris-gb-disasm#2]
Hello!

I've been working with this disassembly for a little while now, however I noticed that you don't have any license attached to it. From my understanding not having a license associated with your code automatically means you reserve all copyright. This means that nobody will be able to fork, modify, and distribute without explicit permission from you. Was this intentional? If not, would you consider licensing under an open source license instead?

Cheers.

**Comment by vinheim3** [comment]
Hi!

I've added a license now. It wasn't intentional, just not a thing I knew much about. I've added it now

**Comment by Y2K-x** [comment]
> Hi!
> 
> I've added a license now. It wasn't intentional, just not a thing I knew much about. I've added it now

Much appreciated! 👍
